version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=song
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/data/postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
